version: '3'

services:
  gdal-python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shp2pgsql
    volumes:
      - ./src:/usr/src/app
      - ./data:/data
    working_dir: /usr/src/app
    tty: true